# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 205)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 501, 131))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_check_filename_choice = QtWidgets.QToolButton(self.tab)
        self.btn_check_filename_choice.setGeometry(QtCore.QRect(460, 10, 25, 19))
        self.btn_check_filename_choice.setObjectName("btn_check_filename_choice")
        self.check_filename = QtWidgets.QLineEdit(self.tab)
        self.check_filename.setGeometry(QtCore.QRect(100, 10, 351, 20))
        self.check_filename.setObjectName("check_filename")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.btn_check_start = QtWidgets.QPushButton(self.tab)
        self.btn_check_start.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.btn_check_start.setObjectName("btn_check_start")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(110, 40, 61, 16))
        self.label_3.setObjectName("label_3")
        self.id_output = QtWidgets.QLineEdit(self.tab)
        self.id_output.setGeometry(QtCore.QRect(180, 40, 113, 20))
        self.id_output.setReadOnly(True)
        self.id_output.setObjectName("id_output")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.new_ans_name = QtWidgets.QLineEdit(self.tab_2)
        self.new_ans_name.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.new_ans_name.setObjectName("new_ans_name")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.label_5.setObjectName("label_5")
        self.data_name = QtWidgets.QLineEdit(self.tab_2)
        self.data_name.setGeometry(QtCore.QRect(70, 40, 113, 20))
        self.data_name.setObjectName("data_name")
        self.btn_data_choice = QtWidgets.QToolButton(self.tab_2)
        self.btn_data_choice.setGeometry(QtCore.QRect(190, 40, 25, 19))
        self.btn_data_choice.setObjectName("btn_data_choice")
        self.btn_create_ans = QtWidgets.QPushButton(self.tab_2)
        self.btn_create_ans.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.btn_create_ans.setObjectName("btn_create_ans")
        self.tabWidget.addTab(self.tab_2, "")
        self.ans_name = QtWidgets.QLineEdit(self.centralwidget)
        self.ans_name.setGeometry(QtCore.QRect(80, 10, 341, 20))
        self.ans_name.setObjectName("ans_name")
        self.btn_ans_choice = QtWidgets.QToolButton(self.centralwidget)
        self.btn_ans_choice.setGeometry(QtCore.QRect(430, 10, 25, 19))
        self.btn_ans_choice.setObjectName("btn_ans_choice")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.label_2.setObjectName("label_2")
        self.btn_ans_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ans_confirm.setGeometry(QtCore.QRect(460, 10, 71, 23))
        self.btn_ans_confirm.setObjectName("btn_ans_confirm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ANS Authentication"))
        self.btn_check_filename_choice.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Звуковой файл:"))
        self.btn_check_start.setText(_translate("MainWindow", "Подвтердить"))
        self.label_3.setText(_translate("MainWindow", "ID диктора:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Аутентификация"))
        self.new_ans_name.setText(_translate("MainWindow", "NewNet"))
        self.label_4.setText(_translate("MainWindow", "Имя:"))
        self.label_5.setText(_translate("MainWindow", "Данные:"))
        self.btn_data_choice.setText(_translate("MainWindow", "..."))
        self.btn_create_ans.setText(_translate("MainWindow", "Создать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Создать сеть"))
        self.btn_ans_choice.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Файл сети:"))
        self.btn_ans_confirm.setText(_translate("MainWindow", "Загрузить"))

